# Generated by Django 5.2.9 on 2025-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Living Room Camera', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Example: 192.168.1.200', protocol='IPv4')),
                ('port', models.CharField(default='554', help_text='Default RTSP port is 554', max_length=10)),
                ('username', models.CharField(help_text='Camera Username', max_length=100)),
                ('password', models.CharField(help_text='Camera Password', max_length=100)),
                ('stream_path_hd', models.CharField(default='/stream1', help_text='Path for High Quality (e.g., /stream1 or /main)', max_length=100)),
                ('stream_path_sd', models.CharField(default='/stream2', help_text='Path for Low Quality (e.g., /stream2 or /sub)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
