; Inno Setup script — builds a one-click Windows installer for the DigiFlow desktop app.
; Compile with:  ISCC.exe installer.iss   (output: installer_output\DigiFlow-Setup.exe)
; Prerequisite:  build dist\DigiFlow first  (see docs/BUILD_EXE.md)

#define AppName "DigiFlow"
#define AppVer "1.0.0"
#define AppPublisher "DigiFlow"
#define AppExe "DigiFlow.exe"

[Setup]
AppId={{A7F2C9E1-POS0-4B3A-9D5E-POSSYSTEM0001}
AppName={#AppName}
AppVersion={#AppVer}
AppPublisher={#AppPublisher}
DefaultDirName={code:GetDefaultDir}
DefaultGroupName=DigiFlow
DisableProgramGroupPage=yes
; The app first shipped as "Wholesale POS System" and was later renamed to DigiFlow, but
; AppId deliberately stayed the same so upgrades keep working. Inno's default is to reuse
; whatever folder and Start Menu group the PREVIOUS install registered, so an upgrade
; silently landed back in "Program Files\Wholesale POS System" with the old name in the
; Start Menu — the rename only ever showed up on machines that had never had the product.
; Turning both off makes DefaultDirName/DefaultGroupName authoritative; GetDefaultDir below
; still honours a genuinely custom folder an admin picked.
UsePreviousAppDir=no
UsePreviousGroup=no
OutputDir=installer_output
OutputBaseFilename=DigiFlow-Setup
SetupIconFile=app_icon.ico
UninstallDisplayIcon={app}\{#AppExe}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
; A POS terminal is per-machine software:
PrivilegesRequired=admin

[Languages]
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; Ship the entire PyInstaller onedir output — but NEVER the runtime data\ folder
; (that's the customer's own database/media, created fresh on first launch).
Source: "dist\DigiFlow\*"; DestDir: "{app}"; Excludes: "data\*,data,*.log"; Flags: recursesubdirs createallsubdirs ignoreversion
; PostgreSQL server installer — extracted to a temp folder, run silently, then deleted
; (deleteafterinstall), so ~350 MB never lingers in Program Files. Only extracted at all
; when the customer actually opted into installing it (Check), so a SQLite install pays
; no time cost for it.
Source: "vendor\postgresql-setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: ShouldInstallPostgres

[Dirs]
; The app writes its database/media here; keep it on uninstall (don't delete customer data).
Name: "{app}\data"; Permissions: users-modify

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"; WorkingDir: "{app}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
; Silent PostgreSQL server install. --superpassword must match what goes into
; db_config.json, or the app won't be able to log in afterwards. stackbuilder is
; disabled: it's an interactive add-on downloader with no place in an unattended install.
Filename: "{tmp}\postgresql-setup.exe"; \
  Parameters: "--mode unattended --unattendedmodeui minimal --disable-components stackbuilder --superpassword ""{code:GetPgPassword}"" --serverport {code:GetPgPort}"; \
  StatusMsg: "جارٍ تثبيت PostgreSQL (قد يستغرق عدة دقائق)... / Installing PostgreSQL..."; \
  Check: ShouldInstallPostgres; Flags: waituntilterminated
Filename: "{app}\{#AppExe}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove only the program; the customer's data\ folder is intentionally preserved.
Type: filesandordirs; Name: "{app}\_internal"
; The DB connection file is generated by this installer, so it goes with the program.
; (It holds no customer data — just where to find the database.)
Type: files; Name: "{app}\db_config.json"

[Code]
{ ── Optional PostgreSQL setup ──────────────────────────────────────────────────
  The app ships on SQLite, which needs zero setup and is fine for a single-PC shop.
  A branch running several tills/phones against one server is better on PostgreSQL,
  so offer it here and write the connection details to db_config.json, which
  pos_launcher.py reads at startup (see _load_db_config there).
  Leaving the checkbox unticked keeps the SQLite default. }

var
  PgPage: TInputQueryWizardPage;
  PgOptPage: TInputOptionWizardPage;
  { Where a previous version installed itself, read BEFORE this install rewrites the
    uninstall key. Empty string on a first-time install. }
  PrevDir: string;

const
  OLD_PRODUCT_NAME = 'Wholesale POS System';
  UNINST_KEY = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A7F2C9E1-POS0-4B3A-9D5E-POSSYSTEM0001}_is1';

{ Setup runs 32-bit while the app installs 64-bit, so a previous install's key may sit in
  either registry view depending on which build wrote it — check both. }
function ReadPreviousAppDir(): string;
var
  S: string;
begin
  Result := '';
  if RegQueryStringValue(HKLM, UNINST_KEY, 'Inno Setup: App Path', S) then
    Result := S
  else if IsWin64 and RegQueryStringValue(HKLM64, UNINST_KEY, 'Inno Setup: App Path', S) then
    Result := S;
end;

function InitializeSetup(): Boolean;
begin
  PrevDir := ReadPreviousAppDir();
  Result := True;
end;

{ Keep a deliberately-chosen custom folder (someone who installed to D:\DigiFlow meant it),
  but never inherit the old product-name folder — that is the thing being fixed here. }
function GetDefaultDir(Param: string): string;
begin
  if (PrevDir <> '') and
     (CompareText(ExtractFileName(RemoveBackslash(PrevDir)), OLD_PRODUCT_NAME) <> 0) then
    Result := RemoveBackslash(PrevDir)
  else
    Result := ExpandConstant('{autopf}\DigiFlow');
end;

{ Retire an old-named install once the new one is in place. }
procedure MigrateFromOldFolder();
var
  ResultCode: Integer;
  NewDir, OldGroup: string;
begin
  NewDir := RemoveBackslash(ExpandConstant('{app}'));
  if (PrevDir = '') or (not DirExists(PrevDir)) or
     (CompareText(RemoveBackslash(PrevDir), NewDir) = 0) then
    Exit;

  { The customer's database normally lives in C:\ProgramData\DigiFlow\data, because a
    cashier running the app without admin rights cannot write inside Program Files. But an
    install that was ever launched as administrator keeps it in the program folder
    deleting the old folder without checking would wipe out the shop's entire database.
    So copy it across first, and if that copy fails for any reason leave the old folder
    completely untouched rather than risk it. }
  if FileExists(PrevDir + '\data\db.sqlite3') and
     (not FileExists(NewDir + '\data\db.sqlite3')) then
  begin
    if (not Exec('cmd.exe',
                 '/c xcopy "' + RemoveBackslash(PrevDir) + '\data" "' + NewDir + '\data" /E /I /Y /Q',
                 '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
      Exit;
  end;

  DelTree(RemoveBackslash(PrevDir), True, True, True);

  OldGroup := ExpandConstant('{commonprograms}') + '\' + OLD_PRODUCT_NAME;
  if DirExists(OldGroup) then
    DelTree(OldGroup, True, True, True);
end;

{ Windows cannot delete a running .exe, so if the old-named install was open while the
  upgrade ran, its program files survive as a dead half-gigabyte copy — and a shortcut
  someone pinned to the taskbar still launches that stale build, which then looks like
  the update did nothing. The registry now points at the new folder, so the migration
  above will never look at the old one again; clean it up here instead. Only ever when
  its data folder is already gone, i.e. the database was migrated and nothing is at risk. }
procedure PurgeLegacyFolder();
var
  Legacy: string;
begin
  Legacy := RemoveBackslash(ExpandConstant('{commonpf}') + '\' + OLD_PRODUCT_NAME);
  if (not DirExists(Legacy)) or
     (CompareText(Legacy, RemoveBackslash(ExpandConstant('{app}'))) = 0) then
    Exit;
  if DirExists(Legacy + '\data') then
    Exit;
  DelTree(Legacy, True, True, True);
end;

{ Is a PostgreSQL server already on this machine? Used to decide whether to offer
  installing the bundled one — installing a second server over an existing one would
  collide on the port and confuse the customer. }
function IsPostgresPresent(): Boolean;
begin
  Result := DirExists(ExpandConstant('{commonpf}\PostgreSQL')) or
            DirExists(ExpandConstant('{commonpf32}\PostgreSQL'));
end;

procedure InitializeWizard();
begin
  PgOptPage := CreateInputOptionPage(wpSelectTasks,
    'قاعدة البيانات / Database',
    'اختر طريقة تخزين البيانات',
    'اتركهما فارغين لاستخدام قاعدة البيانات الداخلية (SQLite) — لا تحتاج أي إعداد، ومناسبة لجهاز واحد.' + #13#10#13#10 +
    'الخيار الأول: البرنامج يخزّن بياناته في PostgreSQL بدل SQLite (لو الفرع فيه أكثر من جهاز/كاشير على نفس البيانات).' + #13#10 +
    'الخيار الثاني: يثبّت برنامج PostgreSQL نفسه على هذا الجهاز — اختره فقط لو PostgreSQL غير مثبّت هنا.' + #13#10 +
    'الخيار الثاني لا يعمل إلا مع الأول.' + #13#10#13#10 +
    'Leave both unticked to use the built-in SQLite database (no setup). The first ' +
    'option makes the app STORE its data in PostgreSQL; the second INSTALLS the ' +
    'PostgreSQL software itself. The second only applies together with the first.',
    False, False);
  PgOptPage.Add('١) خزّن البيانات في PostgreSQL بدل SQLite / Store data in PostgreSQL');
  if IsPostgresPresent() then
    PgOptPage.Add('٢) ثبّت برنامج PostgreSQL على هذا الجهاز — (تم العثور على نسخة مثبّتة بالفعل) / Install PostgreSQL software (already found on this PC)')
  else
    PgOptPage.Add('٢) ثبّت برنامج PostgreSQL على هذا الجهاز — (غير مثبّت، مطلوب) / Install PostgreSQL software (not found — required)');
  PgOptPage.Values[0] := False;
  { Pre-tick installing the server only when none was found — if one is already here,
    installing another would fight over the port. }
  PgOptPage.Values[1] := not IsPostgresPresent();

  PgPage := CreateInputQueryPage(PgOptPage.ID,
    'إعدادات PostgreSQL', 'بيانات الاتصال بقاعدة البيانات',
    'لو اخترت تثبيت الخادم، ستُستخدم كلمة المرور هذه لحساب postgres.' + #13#10 +
    'وسيتم إنشاء قاعدة البيانات تلقائياً عند أول تشغيل لو لم تكن موجودة.' + #13#10 +
    'If installing the server, this password is set for the postgres account. The ' +
    'database itself is created automatically on first launch.');
  PgPage.Add('اسم قاعدة البيانات / Database name:', False);
  PgPage.Add('المستخدم / User:', False);
  PgPage.Add('كلمة المرور / Password:', True);
  PgPage.Add('الخادم / Host:', False);
  PgPage.Add('المنفذ / Port:', False);
  PgPage.Values[0] := 'digiflow';
  PgPage.Values[1] := 'postgres';
  PgPage.Values[3] := '127.0.0.1';
  PgPage.Values[4] := '5432';
end;

{ Skip the connection page entirely unless PostgreSQL was chosen. }
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := (PageID = PgPage.ID) and (not PgOptPage.Values[0]);
end;

{ Only install the bundled server when PostgreSQL was chosen AND the customer asked for
  it. Referenced by both [Files] and [Run]. }
function ShouldInstallPostgres(): Boolean;
begin
  Result := PgOptPage.Values[0] and PgOptPage.Values[1];
end;

function GetPgPassword(Param: string): string;
begin
  Result := PgPage.Values[2];
end;

function GetPgPort(Param: string): string;
begin
  Result := PgPage.Values[4];
end;

{ A blank password would make the silent server install produce an account the app then
  can't log into — catch it on the page itself rather than failing much later. }
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  { Choosing "store data in PostgreSQL" on a PC that has no PostgreSQL, without also
    ticking "install it", produces an app that cannot start — catch that here instead of
    letting them discover it after the install finishes. }
  if (CurPageID = PgOptPage.ID) and PgOptPage.Values[0] and (not PgOptPage.Values[1])
     and (not IsPostgresPresent()) then
  begin
    if MsgBox('لم يتم العثور على PostgreSQL على هذا الجهاز، ولم تختر تثبيته.' + #13#10 +
              'البرنامج لن يستطيع العمل بدونه.' + #13#10#13#10 +
              'هل تريد المتابعة على أي حال؟' + #13#10#13#10 +
              'PostgreSQL was not found and you chose not to install it — the app will ' +
              'not be able to start. Continue anyway?',
              mbConfirmation, MB_YESNO) = IDNO then
      Result := False;
    Exit;
  end;

  if (CurPageID = PgPage.ID) then
  begin
    if Trim(PgPage.Values[2]) = '' then
    begin
      MsgBox('من فضلك أدخل كلمة مرور لقاعدة البيانات.' + #13#10 +
             'Please enter a database password.', mbError, MB_OK);
      Result := False;
    end
    else if Trim(PgPage.Values[0]) = '' then
    begin
      MsgBox('من فضلك أدخل اسم قاعدة البيانات.' + #13#10 +
             'Please enter a database name.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function JsonEscape(const S: string): string;
begin
  Result := S;
  StringChangeEx(Result, '\', '\\', True);
  StringChangeEx(Result, '"', '\"', True);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Json: string;
begin
  { ssDone runs after the [Run] entries, so this is where we can tell whether the
    bundled PostgreSQL install actually succeeded. Without this check a failed silent
    install would go unnoticed until the app refused to start later with a connection
    error, and nobody would connect that back to the installer. }
  if CurStep = ssDone then
  begin
    if ShouldInstallPostgres() and (not IsPostgresPresent()) then
      MsgBox('لم يكتمل تثبيت PostgreSQL.' + #13#10#13#10 +
             'ثبّت PostgreSQL يدوياً ثم شغّل البرنامج مرة أخرى، أو أعد التثبيت واختر ' +
             'قاعدة البيانات الداخلية (SQLite).' + #13#10#13#10 +
             'PostgreSQL was not installed. Install it manually and start the app again, ' +
             'or re-run this installer and choose the built-in SQLite database.',
             mbError, MB_OK);
    Exit;
  end;

  if CurStep <> ssPostInstall then
    Exit;

  MigrateFromOldFolder();
  PurgeLegacyFolder();

  if PgOptPage.Values[0] then
  begin
    Json :=
      '{' + #13#10 +
      '  "engine": "postgres",' + #13#10 +
      '  "name": "'     + JsonEscape(PgPage.Values[0]) + '",' + #13#10 +
      '  "user": "'     + JsonEscape(PgPage.Values[1]) + '",' + #13#10 +
      '  "password": "' + JsonEscape(PgPage.Values[2]) + '",' + #13#10 +
      '  "host": "'     + JsonEscape(PgPage.Values[3]) + '",' + #13#10 +
      '  "port": "'     + JsonEscape(PgPage.Values[4]) + '"' + #13#10 +
      '}' + #13#10;
    SaveStringToFile(ExpandConstant('{app}\db_config.json'), Json, False);
  end
  else
    { Unticked on a REinstall must actively go back to SQLite — a stale config file
      left behind would silently keep pointing at the old PostgreSQL server. }
    DeleteFile(ExpandConstant('{app}\db_config.json'));
end;
