# Generated by Django 5.2.9 on 2026-01-21 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('CASH_DRAWER', 'درج الكاشير'), ('SAFE', 'الخزنة الرئيسية'), ('BANK', 'حساب بنكي'), ('VODAFONE_CASH', 'فودافون كاش'), ('INSTAPAY', 'إنستا باي')], max_length=20, verbose_name='نوع الحساب')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='DailyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('start_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رصيد البداية (في الدرج)')),
                ('total_sales_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبيعات الكاش (نظام)')),
                ('total_sales_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبيعات فيزا (نظام)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المصروفات')),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المسحوبات')),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المفروض يكون في الدرج')),
                ('actual_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='العد الفعلي (الجرد)')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العجز / الزيادة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإغلاق')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تم الإغلاق')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'إيراد خارجي (غير مبيعات)'), ('EXPENSE', 'مصروفات تشغيل'), ('WITHDRAWAL', 'سحب مالك / مسحوبات'), ('DEPOSIT', 'إيداع في الخزنة'), ('TRANSFER', 'تحويل بين الحسابات')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحركة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account', verbose_name='الحساب المتأثر')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='قام بالحركة')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.dailyshift', verbose_name='الشيفت')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='financial.account', verbose_name='إلى حساب (في حالة التحويل)')),
            ],
        ),
    ]
