# Generated by Django 5.2.9 on 2026-01-24 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='قام بالحركة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.dailyshift', verbose_name='الشيفت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'إيراد مبيعات (أوردر)'), ('INCOME', 'إيراد خارجي (غير مبيعات)'), ('EXPENSE', 'مصروفات تشغيل'), ('WITHDRAWAL', 'سحب مالك / مسحوبات'), ('DEPOSIT', 'إيداع في الخزنة'), ('TRANSFER', 'تحويل بين الحسابات')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
