# Generated by Django 5.2.9 on 2026-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'إيراد مبيعات (أوردر)'), ('INCOME', 'إيراد خارجي (غير مبيعات)'), ('EXPENSE', 'مصروفات تشغيل'), ('WITHDRAWAL', 'سحب مالك / مسحوبات'), ('REFUND', 'مرتجع بيع'), ('DEPOSIT', 'إيداع في الخزنة'), ('TRANSFER', 'تحويل بين الحسابات'), ('SUPPLIER_PAYMENT', 'سند صرف مورد')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
