# Generated by Django 6.0.5 on 2026-05-29 18:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_shiftemaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='financial.account', verbose_name='الحساب الأب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'الأصول'), ('LIABILITY', 'الخصوم / الالتزامات'), ('EQUITY', 'حقوق الملكية'), ('REVENUE', 'الإيرادات'), ('EXPENSE', 'المصروفات'), ('CASH_DRAWER', 'درج الكاشير'), ('SAFE', 'الخزنة الرئيسية'), ('BANK', 'حساب بنكي'), ('VODAFONE_CASH', 'فودافون كاش'), ('INSTAPAY', 'إنستا باي')], max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم القيد / المرجع')),
                ('description', models.TextField(verbose_name='البيان / الوصف')),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الترحيل')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل / معتمد'), ('REVERSED', 'ملغى / معكس')], default='DRAFT', max_length=10, verbose_name='حالة القيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='منشئ القيد')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='financial.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financial.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'بند قيد',
                'verbose_name_plural': 'بنود القيود',
            },
        ),
    ]
