# Generated by Django 6.0.5 on 2026-05-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_account_code_account_parent_and_more'),
    ]

    operations = [
    ]
