# Generated by Django 6.0.5 on 2026-05-29 19:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_add_journal_entry_to_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العرض / الخصم')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية (%)'), ('FIXED', 'مبلغ ثابت (ج.م)')], default='PERCENTAGE', max_length=15, verbose_name='نوع الخصم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الحد الأدنى لقيمة الفاتورة لتطبيق العرض')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ بداية العرض')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ نهاية العرض')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود كوبون الخصم (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'عرض وخصم',
                'verbose_name_plural': 'العروض والخصومات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الحوافز والبدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الخصومات والجزاءات')),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='صافي المرتب')),
                ('pay_period', models.CharField(max_length=50, verbose_name='شهر / فترة الصرف')),
                ('status', models.CharField(choices=[('PENDING', 'معلق / مستحق'), ('PAID', 'تم الصرف / مدفوع')], default='PENDING', max_length=15, verbose_name='حالة الصرف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('paid_from', models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['CASH_DRAWER', 'SAFE', 'BANK']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.account', verbose_name='حساب الدفع')),
            ],
            options={
                'verbose_name': 'راتب موظف',
                'verbose_name_plural': 'رواتب الموظفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
