# Generated by Django 6.0.5 on 2026-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_dealdiscount_alter_journalentry_id_and_more'),
        ('products', '0015_alter_purchaseinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdiscount',
            name='apply_to_all',
            field=models.BooleanField(default=True, verbose_name='تطبيق على كل المنتجات'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='منتجات العرض المحددة'),
        ),
    ]
