# Generated by Django 6.0.5 on 2026-05-29 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_dealdiscount_apply_to_all_dealdiscount_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['-created_at'], 'verbose_name': 'إعداد راتب موظف', 'verbose_name_plural': 'إعدادات رواتب الموظفين'},
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='paid_from',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='pay_period',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='status',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
    ]
