# Generated by Django 6.0.5 on 2026-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_alter_employeesalary_options_and_more'),
        ('licensing', '0005_systemlicense_grace_period_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_shifts', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_discounts', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='shiftemaillog',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_email_logs', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='licensing.masterstore', verbose_name='Master Store'),
        ),
    ]
