# Generated by Django 6.0.5 on 2026-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_account_master_store_dailyshift_master_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='dealdiscount',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='shiftemaillog',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='master_store',
        ),
    ]
