# Generated by Django 6.0.5 on 2026-06-12 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_remove_account_master_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdiscount',
            name='buy_n_qty',
            field=models.PositiveIntegerField(default=0, help_text='لعرض اشتري N بسعر واحد', verbose_name='كمية N للعرض'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='buy_x_qty',
            field=models.PositiveIntegerField(default=0, help_text='لعرض اشتري X واحصل على Y', verbose_name='اشتري كمية (X)'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='for_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='السعر الإجمالي لـ N قطعة'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='get_y_qty',
            field=models.PositiveIntegerField(default=0, help_text='الكمية المجانية عند الشراء', verbose_name='احصل على كمية مجاناً (Y)'),
        ),
        migrations.AddField(
            model_name='dealdiscount',
            name='promo_type',
            field=models.CharField(choices=[('discount', 'خصم عادي (% أو مبلغ ثابت)'), ('buy_x_get_y', 'اشتري X واحصل على Y مجاناً'), ('buy_n_for_price', 'اشتري N بسعر X (مثل: 3 بـ 50)')], default='discount', max_length=20, verbose_name='نوع العرض'),
        ),
    ]
