# Generated by Django 6.0.5 on 2026-06-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_market_features_phase1'),
        ('products', '0021_market_features_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdiscount',
            name='get_products',
            field=models.ManyToManyField(blank=True, related_name='free_promotions', to='products.product', verbose_name='المنتجات المجانية (للعرض اشتري X واحصل على Y)'),
        ),
        migrations.AlterField(
            model_name='dealdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='منتجات العرض المحددة (الشراء)'),
        ),
    ]
