# Generated by Django 5.2.9 on 2026-06-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_market_features_phase1'),
        ('financial', '0019_dealdiscount_get_products_and_more'),
        ('products', '0023_clamp_negative_stock'),
        ('sales', '0020_remove_cashsettlement_master_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='crm.customerpayment', verbose_name='دفعة العميل المصدر'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='sales.expense', verbose_name='المصروف المصدر'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='sales.order', verbose_name='فاتورة البيع المصدر'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='sales.returninvoice', verbose_name='مرتجع البيع المصدر'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='products.supplierpayment', verbose_name='سند المورد المصدر'),
        ),
    ]
