# Generated by Django 5.2.9 on 2026-06-13 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_backfill_transaction_order_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_up_to', models.DateField(blank=True, null=True, verbose_name='مغلق حتى تاريخ')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أغلقها')),
            ],
            options={
                'verbose_name': 'إغلاق الفترة المحاسبية',
                'verbose_name_plural': 'إغلاق الفترات المحاسبية',
            },
        ),
    ]
