# Generated by Django 5.2.9 on 2026-06-22 18:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_periodlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة السلفة')),
                ('per_period_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = خصم كامل المبلغ دفعة واحدة', max_digits=10, verbose_name='القسط الشهري')),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المتبقي')),
                ('date_taken', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السلفة')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تم السداد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='الشهر')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='البدلات الثابتة')),
                ('days_absent', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='أيام الغياب')),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم السلف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوع')], default='draft', max_length=10, verbose_name='الحالة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('net_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الصافي المدفوع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('paid_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='financial.account', verbose_name='حساب الصرف')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['-period_month', '-created_at'],
                'unique_together': {('employee', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='PayslipAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bonus', 'حافز / بونص'), ('overtime', 'أوفرتايم'), ('deduction', 'خصم'), ('penalty', 'جزاء')], max_length=12, verbose_name='النوع')),
                ('label', models.CharField(blank=True, default='', max_length=150, verbose_name='البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='financial.payslip', verbose_name='القسيمة')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
