# Generated by Django 5.2.9 on 2026-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_employeeadvance_payslip_payslipadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='opening_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الفتح'),
        ),
    ]
