# Generated by Django 5.2.9 on 2026-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_dailyshift_opening_notes'),
        ('products', '0033_alter_product_price_semi_wholesale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdiscount',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.category', verbose_name='الأقسام المشمولة بالعرض'),
        ),
    ]
