# Generated by Django 5.2.15 on 2026-08-08 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_dealdiscount_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير (متضمنة الانصراف المبكر)'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غياب'), ('excused', 'غياب بعذر'), ('leave', 'إجازة'), ('holiday', 'عطلة رسمية'), ('day_off', 'يوم راحة')], default='present', max_length=10, verbose_name='الحالة')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_departure_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الانصراف المبكر')),
                ('deduct_salary', models.BooleanField(default=False, verbose_name='يخصم من الراتب')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور والغياب',
                'ordering': ['-date', 'employee_id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
