# Generated by Django 5.2.15 on 2026-08-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_payslip_late_minutes_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='locked_by_manual_edit',
            field=models.BooleanField(default=False, verbose_name='مقفل بتعديل يدوي'),
        ),
    ]
