# Generated by Django 5.2.15 on 2026-08-22 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0027_attendancerecord_locked_by_manual_edit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'employee_id', 'shift_index'], 'verbose_name': 'سجل حضور', 'verbose_name_plural': 'سجلات الحضور والغياب'},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='رقم الشيفت'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date', 'shift_index')},
        ),
    ]
