# Generated by Django 5.2.15 on 2026-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshift',
            name='last_order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='آخر رقم فاتورة في الشيفت'),
        ),
    ]
