# Generated by Django 5.2.15 on 2026-08-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_seed_open_shift_order_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advances', to='financial.account', verbose_name='صُرفت من حساب'),
        ),
    ]
