# Generated by Django 5.2.15 on 2026-09-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_employeeadvance_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advance', to='financial.transaction', verbose_name='حركة الصرف'),
        ),
    ]
