# Generated by Django 5.2.9 on 2026-04-08 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدور')),
                ('permissions', models.JSONField(default=dict, verbose_name='الصلاحيات (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('EXPORT', 'تصدير'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الحركة')),
                ('module', models.CharField(max_length=50, verbose_name='الوحدة (Module)')),
                ('description', models.TextField(verbose_name='وصف الحركة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الـ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='المتصفح والجهاز')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='البيانات قبل التعديل')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='البيانات بعد التعديل')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحركة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفرع')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('preferred_lang', models.CharField(default='ar', max_length=10, verbose_name='لغة الواجهة')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50, verbose_name='المنطقة الزمنية')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='أكمل التهيئة؟')),
                ('last_known_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP مسجل')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='الأدوار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان الـ IP')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='مشبوه (Flagged)')),
                ('is_whitelisted', models.BooleanField(default=False, verbose_name='في القائمة البيضاء')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='في القائمة السوداء')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أول ظهور')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ip_address')},
            },
        ),
    ]
