# Generated by Django 5.2.9 on 2026-04-08 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='المسار (URL)')),
                ('exception_type', models.CharField(max_length=255, verbose_name='نوع الخطأ')),
                ('message', models.TextField(verbose_name='رسالة الخطأ')),
                ('traceback', models.TextField(verbose_name='تفاصيل الخطأ (Traceback)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدوث')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
