# Generated by Django 5.2.9 on 2026-04-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemerror',
            name='source',
            field=models.CharField(choices=[('BACKEND', 'خلفية النظام (Django)'), ('FRONTEND', 'واجهة النظام (JavaScript)')], default='BACKEND', max_length=20, verbose_name='مصدر الخطأ'),
        ),
    ]
