# Generated by Django 5.2.9 on 2026-04-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemerror_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direct_permissions',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='صلاحيات مباشرة'),
        ),
    ]
