# Generated by Django 6.0.5 on 2026-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_direct_permissions'),
        ('products', '0010_product_scientific_name_product_strips_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_warehouses',
            field=models.ManyToManyField(blank=True, to='products.warehouse', verbose_name='المخازن المسموحة'),
        ),
    ]
