# Generated by Django 6.0.5 on 2026-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_allowed_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='رتبة المالك (Master)'),
        ),
    ]
