# Generated by Django 6.0.5 on 2026-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_master_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='master_store',
        ),
    ]
