# Generated by Django 5.2.9 on 2026-06-15 06:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_master_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_price',
            field=models.BooleanField(default=True, verbose_name='السماح بتعديل السعر في نقطة البيع'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sell_below_cost',
            field=models.BooleanField(default=False, verbose_name='السماح بالبيع تحت سعر التكلفة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='أقصى نسبة خصم مسموحة %'),
        ),
    ]
