# Generated by Django 5.2.9 on 2026-06-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_can_edit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.JSONField(blank=True, default=list, verbose_name='الاختصارات المفضلة'),
        ),
    ]
