# Generated by Django 5.2.9 on 2026-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_change_unit',
            field=models.BooleanField(default=True, verbose_name='السماح بتغيير وحدة البيع في الكاشير'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sell_below_sale_price',
            field=models.BooleanField(default=True, verbose_name='السماح بالبيع تحت سعر البيع (القطاعي)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sell_below_zero_stock',
            field=models.BooleanField(default=False, verbose_name='السماح بالبيع برصيد سالب (تحت الصفر)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_profit',
            field=models.BooleanField(default=False, verbose_name='إظهار الربح على الفواتير والتقارير'),
        ),
    ]
