# Generated by Django 5.2.9 on 2026-06-21 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_can_change_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('over_discount', 'تجاوز حد الخصم'), ('below_cost', 'البيع تحت سعر التكلفة'), ('below_sale_price', 'البيع تحت سعر القطاعي'), ('change_unit', 'تغيير وحدة البيع'), ('below_zero_stock', 'البيع برصيد سالب'), ('over_credit_limit', 'تجاوز حد ائتمان العميل')], max_length=30, verbose_name='نوع التجاوز')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('note', models.TextField(blank=True, default='', verbose_name='سبب الطلب')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='المعتمِد')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
            ],
            options={
                'verbose_name': 'طلب اعتماد',
                'verbose_name_plural': 'طلبات الاعتماد',
                'ordering': ['-created_at'],
            },
        ),
    ]
