# Generated by Django 5.2.9 on 2026-06-22 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _dedupe_phones(apps, schema_editor):
    """Before adding the UNIQUE constraint: blank phones → NULL (NULLs don't collide), and
    null out any remaining duplicate non-null phones (keep the lowest-pk holder)."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(phone='').update(phone=None)
    seen = set()
    for prof in UserProfile.objects.exclude(phone__isnull=True).order_by('pk'):
        if prof.phone in seen:
            prof.phone = None
            prof.save(update_fields=['phone'])
        else:
            seen.add(prof.phone)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedupe_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
