# Generated by Django 5.2.15 on 2026-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_max_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_landing',
            field=models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('waiter', 'شاشة الويتر (POS)'), ('cashier', 'شاشة الكاشير')], default='dashboard', max_length=10, verbose_name='الشاشة الافتراضية بعد الدخول'),
        ),
    ]
