# Generated by Django 5.2.15 on 2026-07-12 19:45

from django.db import migrations, models


def reset_untouched_default_to_auto(apps, schema_editor):
    # default_landing was previously dead code (never read at login), so every profile
    # still sitting on the model's old default 'dashboard' was never a deliberate admin
    # choice — safe to flip those to the new 'auto' (permission-based) behavior. Any
    # profile an admin explicitly set to 'waiter'/'cashier' is left untouched; it will
    # now actually be honored for the first time by get_best_landing_url().
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(default_landing='dashboard').update(default_landing='auto')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_cafe_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_landing',
            field=models.CharField(choices=[('auto', 'تلقائي (حسب صلاحيات المستخدم)'), ('dashboard', 'لوحة التحكم'), ('waiter', 'شاشة الويتر (POS)'), ('cashier', 'شاشة الكاشير')], default='auto', max_length=10, verbose_name='الشاشة الافتراضية بعد الدخول'),
        ),
        migrations.RunPython(reset_untouched_default_to_auto, migrations.RunPython.noop),
    ]
