# Generated by Django 5.2.15 on 2026-08-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_default_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_order_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع الطلبات المسموحة'),
        ),
    ]
