# Generated by Django 5.2.15 on 2026-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_allowed_order_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allowed_order_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع الطلبات المسموحة'),
        ),
    ]
