# Generated by Django 5.2.15 on 2026-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_role_allowed_order_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='kind',
            field=models.CharField(choices=[('over_discount', 'تجاوز حد الخصم'), ('below_cost', 'البيع تحت سعر التكلفة'), ('below_sale_price', 'البيع تحت سعر القطاعي'), ('change_unit', 'تغيير وحدة البيع'), ('below_zero_stock', 'البيع برصيد سالب'), ('over_credit_limit', 'تجاوز حد ائتمان العميل'), ('over_expense_limit', 'تجاوز حد اعتماد المصروف اليومي')], max_length=30, verbose_name='نوع التجاوز'),
        ),
    ]
