# Generated by Django 6.0.5 on 2026-05-29 22:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStore',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Store ID')),
                ('public_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Public ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='Store Name')),
                ('store_type', models.CharField(choices=[('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبر ماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type')),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trial', 'Trial')], default='active', max_length=20, verbose_name='License Status')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscription Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Master Store',
                'verbose_name_plural': 'Master Stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLicense',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Store ID')),
                ('store_type', models.CharField(choices=[('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبر ماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscription Expires At')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Settings Locked')),
                ('last_token_used', models.TextField(blank=True, null=True, verbose_name='Last Token Used')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('device_id', models.UUIDField(blank=True, null=True, verbose_name='Local Device ID')),
            ],
            options={
                'verbose_name': 'System License',
                'verbose_name_plural': 'System Licenses',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Device ID')),
                ('device_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Name')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='Device Info')),
                ('is_authorized', models.BooleanField(default=True, verbose_name='Authorized')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Last Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='licensing.masterstore', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token Log ID')),
                ('action', models.CharField(choices=[('CHANGE_STORE_TYPE', 'Change Store Type'), ('DEVICE_AUTHORIZATION', 'Device Authorization'), ('EXTEND_SUBSCRIPTION', 'Extend Subscription'), ('GENERAL_SYSTEM_OVERRIDE', 'General System Override')], max_length=50, verbose_name='Action')),
                ('value', models.TextField(verbose_name='Value')),
                ('token', models.TextField(verbose_name='Activation Token')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('used_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Used By')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to='licensing.masterstore', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Token Log',
                'verbose_name_plural': 'Token Logs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
