# Generated by Django 6.0.5 on 2026-05-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, verbose_name='Dark Mode Enabled'),
        ),
        migrations.AddField(
            model_name='systemlicense',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Enabled Modules'),
        ),
        migrations.AlterField(
            model_name='tokenlog',
            name='action',
            field=models.CharField(choices=[('CHANGE_STORE_TYPE', 'Change Store Type'), ('DEVICE_AUTHORIZATION', 'Device Authorization'), ('EXTEND_SUBSCRIPTION', 'Extend Subscription'), ('GENERAL_SYSTEM_OVERRIDE', 'General System Override'), ('TOGGLE_DARK_MODE', 'Toggle Dark Mode'), ('ENABLE_MODULE', 'Enable Module'), ('DISABLE_MODULE', 'Disable Module')], max_length=50, verbose_name='Action'),
        ),
    ]
