# Generated by Django 6.0.5 on 2026-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_systemlicense_dark_mode_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperAccount',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Developer Account',
                'verbose_name_plural': 'Developer Account',
            },
        ),
    ]
