# Generated by Django 6.0.5 on 2026-05-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_developeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='grace_period_used',
            field=models.BooleanField(default=False, verbose_name='Has Used Grace Period'),
        ),
        migrations.AddField(
            model_name='systemlicense',
            name='license_signature',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='License Signature'),
        ),
    ]
