# Generated by Django 6.0.5 on 2026-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_systemlicense_grace_period_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='grace_period_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grace Period Started At'),
        ),
        migrations.AddField(
            model_name='systemlicense',
            name='system_locked',
            field=models.BooleanField(default=False, verbose_name='System Completely Locked'),
        ),
    ]
