# Generated by Django 6.0.5 on 2026-05-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_systemlicense_grace_period_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duration (Days)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='Currency')),
                ('features', models.JSONField(default=list, verbose_name='Features (JSON array)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mark as Popular')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PURCHASE', 'Purchase'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade'), ('DOWNGRADE', 'Downgrade'), ('EXTENSION', 'Extension'), ('MANUAL', 'Manual Adjustment')], default='PURCHASE', max_length=50, verbose_name='Action')),
                ('old_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Old Expiry Date')),
                ('new_expiry_date', models.DateTimeField(verbose_name='New Expiry Date')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Amount Paid')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.CharField(default='System', max_length=255, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('master_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='licensing.masterstore', verbose_name='Master Store')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
            },
        ),
    ]
