# Generated by Django 5.2.9 on 2026-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_subscriptionplan_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='license_signing_key',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Per-Store Signing Key'),
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
