# Generated by Django 5.2.9 on 2026-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_systemlicense_license_signing_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlog',
            name='action',
            field=models.CharField(choices=[('CHANGE_STORE_TYPE', 'Change Store Type'), ('DEVICE_AUTHORIZATION', 'Device Authorization'), ('EXTEND_SUBSCRIPTION', 'Extend Subscription'), ('GENERAL_SYSTEM_OVERRIDE', 'General System Override'), ('TOGGLE_DARK_MODE', 'Toggle Dark Mode'), ('ENABLE_MODULE', 'Enable Module'), ('DISABLE_MODULE', 'Disable Module'), ('CREATE_MASTER_USER', 'Create Master User')], max_length=50, verbose_name='Action'),
        ),
    ]
