# Generated by Django 5.2.9 on 2026-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0009_resign_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstore',
            name='store_type',
            field=models.CharField(choices=[('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبرماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type'),
        ),
        migrations.AlterField(
            model_name='systemlicense',
            name='store_type',
            field=models.CharField(choices=[('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبرماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type'),
        ),
    ]
