# Generated by Django 5.2.9 on 2026-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0010_alter_masterstore_store_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='used_token_hashes',
            field=models.JSONField(blank=True, default=list, verbose_name='Used Token Fingerprints'),
        ),
    ]
