# Generated by Django 5.2.9 on 2026-06-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0011_systemlicense_used_token_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlog',
            name='action',
            field=models.CharField(choices=[('CHANGE_STORE_TYPE', 'Change Store Type'), ('DEVICE_AUTHORIZATION', 'Device Authorization'), ('EXTEND_SUBSCRIPTION', 'Extend Subscription'), ('GENERAL_SYSTEM_OVERRIDE', 'General System Override'), ('TOGGLE_DARK_MODE', 'Toggle Dark Mode'), ('ENABLE_MODULE', 'Enable Module'), ('DISABLE_MODULE', 'Disable Module'), ('CREATE_MASTER_USER', 'Create Master User'), ('RESET_USER_PASSWORD', 'Reset User Password')], max_length=50, verbose_name='Action'),
        ),
    ]
