# Generated by Django 5.2.15 on 2026-07-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0012_alter_tokenlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstore',
            name='store_type',
            field=models.CharField(choices=[('cafe', 'كافيه ومطعم'), ('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبرماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type'),
        ),
        migrations.AlterField(
            model_name='systemlicense',
            name='store_type',
            field=models.CharField(choices=[('cafe', 'كافيه ومطعم'), ('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبرماركت'), ('general', 'متجر عام')], default='general', max_length=20, verbose_name='Store Type'),
        ),
    ]
