# Generated by Django 5.2.9 on 2025-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='تكس تايل POS', max_length=200, verbose_name='اسم المحل')),
                ('address', models.TextField(blank=True, default='العنوان الافتراضي', verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, default='01000000000', max_length=50, verbose_name='أرقام الهاتف')),
                ('logo_base64', models.TextField(blank=True, null=True, verbose_name='كود اللوجو (Base64)')),
                ('return_policy', models.TextField(blank=True, default='البضاعة المباعة ترد وتستبدل خلال 14 يوم', verbose_name='سياسة الاسترجاع')),
                ('thank_you_text', models.CharField(default='شكراً لزيارتكم', max_length=200, verbose_name='رسالة الشكر')),
                ('show_qr', models.BooleanField(default=True, verbose_name='إظهار QR Code')),
            ],
        ),
    ]
