# Generated by Django 5.2.9 on 2025-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='qr_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='رابط QR Code (اختياري)'),
        ),
    ]
