# Generated by Django 5.2.9 on 2026-01-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsetting_qr_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='printer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطابعة الأساسية (Direct Print)'),
        ),
    ]
