# Generated by Django 5.2.9 on 2026-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemsetting_printer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='notification_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='صوت التنبيه (MP3)'),
        ),
    ]
