# Generated by Django 6.0.5 on 2026-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_systemsetting_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='is_market_type_locked',
            field=models.BooleanField(default=False, verbose_name='قفل نوع المتجر؟ (لا يمكن تغييره)'),
        ),
    ]
