# Generated by Django 5.2.9 on 2026-06-15 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_systemsetting_is_market_type_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي للمنشأة'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة %'),
        ),
    ]
