# Generated by Django 5.2.9 on 2026-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_systemsetting_vat_number_systemsetting_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='قيم ثوابت النظام')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
