# Generated by Django 5.2.9 on 2026-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_systempolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='shop_name',
            field=models.CharField(default='نقطة البيع', max_length=200, verbose_name='اسم المحل'),
        ),
    ]
