# Generated by Django 5.2.15 on 2026-07-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_systemsetting_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='market_type',
            field=models.CharField(choices=[('cafe', 'كافيه ومطعم'), ('clothes', 'ملابس وأقمشة'), ('pharmacy', 'صيدلية'), ('electronics', 'إلكترونيات'), ('grocery', 'بقالة وسوبرماركت'), ('general', 'متجر عام')], default='clothes', max_length=20, verbose_name='نوع المتجر / السوق'),
        ),
    ]
