# Generated by Django 5.2.15 on 2026-07-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_systemsetting_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='vat_included_in_price',
            field=models.BooleanField(default=True, verbose_name='الضريبة مضمنة في الأسعار'),
        ),
    ]
