# Generated by Django 5.2.15 on 2026-07-10 20:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_systemsetting_vat_included_in_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='service_charge_included_in_price',
            field=models.BooleanField(default=False, verbose_name='رسوم الخدمة مضمنة في الأسعار'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة رسوم الخدمة % (صالة فقط)'),
        ),
    ]
