# Generated by Django 5.2.15 on 2026-07-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_systemsetting_service_charge_included_in_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='service_charge_included_in_price',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='service_charge_percent',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='vat_included_in_price',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='vat_rate',
        ),
    ]
