# Generated by Django 5.2.15 on 2026-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_remove_systemsetting_service_charge_included_in_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='ui_color_theme',
            field=models.CharField(choices=[('default', 'الافتراضي (تركواز)'), ('indigo', 'نيلي'), ('emerald', 'زمردي'), ('rose', 'وردي'), ('amber', 'كهرماني'), ('violet', 'بنفسجي'), ('sky', 'سماوي'), ('slate', 'رمادي')], default='default', max_length=20, verbose_name='نظام ألوان الواجهة'),
        ),
    ]
