# Generated by Django 5.2.15 on 2026-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_systemsetting_ui_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='ui_color_theme',
            field=models.CharField(choices=[('default', 'الافتراضي (تركواز)'), ('indigo', 'نيلي'), ('emerald', 'زمردي'), ('rose', 'وردي غامق'), ('pink', 'زهري'), ('amber', 'كهرماني'), ('orange', 'برتقالي'), ('violet', 'بنفسجي'), ('fuchsia', 'فوشيا'), ('sky', 'سماوي'), ('cyan', 'سيان'), ('lime', 'ليموني'), ('slate', 'رمادي'), ('brown', 'بني'), ('beige', 'بيج')], default='default', max_length=20, verbose_name='نظام ألوان الواجهة'),
        ),
    ]
