# Generated by Django 5.2.15 on 2026-08-14 20:12

from django.db import migrations, models


def blank_out_placeholder_address(apps, schema_editor):
    """Existing rows saved before this migration may still literally hold the old
    default text "العنوان الافتراضي" (nobody typed that in — it was the field's own
    prior default) — blank it so it stops printing on receipts as if it were real.
    """
    SystemSetting = apps.get_model('settings', 'SystemSetting')
    SystemSetting.objects.filter(address='العنوان الافتراضي').update(address='')


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_alter_systemsetting_ui_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='العنوان'),
        ),
        migrations.RunPython(blank_out_placeholder_address, migrations.RunPython.noop),
    ]
