# Generated by Django 5.2.15 on 2026-08-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_migrate_payroll_shift_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='shop_name',
            field=models.CharField(default='DigiFlow', max_length=200, verbose_name='اسم المحل'),
        ),
    ]
