# Generated by Django 5.2.15 on 2026-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_alter_systemsetting_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='kitchen_printer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='طابعة المطبخ (طباعة مباشرة للتذاكر)'),
        ),
    ]
