"""
Django settings for textile_pos project.

Generated by 'django-admin startproject' using Django 5.2.9.

Configuration is environment-driven. All security-sensitive values read from
environment variables, falling back to development-safe defaults so local work
keeps running unchanged. In PRODUCTION set at least:

    DJANGO_DEBUG=False
    DJANGO_SECRET_KEY=<a long random string>
    DJANGO_ALLOWED_HOSTS=mekawyerp.shop,www.mekawyerp.shop,167.86.71.246

Optional PostgreSQL (Phase 0.3):
    DJANGO_DB_ENGINE=postgres
    DJANGO_DB_NAME / DJANGO_DB_USER / DJANGO_DB_PASSWORD / DJANGO_DB_HOST / DJANGO_DB_PORT

See .env.example for the full list.
"""

import os
import sys
import logging
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default):
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default):
    val = os.environ.get(name)
    if not val:
        return default
    return [item.strip() for item in val.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the legacy insecure key ONLY for local development.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-u-x7zybg@-fsb9n#o)xi!zc9tmp!=*4zox7&)j6&x+@x6%@^c_',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True to preserve current dev behavior; set DJANGO_DEBUG=False in prod.
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['167.86.71.246', 'mekawyerp.shop', 'www.mekawyerp.shop', 'localhost', '127.0.0.1', '192.168.1.8'],
)

# CSRF trusted origins for the production domains (needed once DEBUG=False behind HTTPS).
CSRF_TRUSTED_ORIGINS = _env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    ['https://mekawyerp.shop', 'https://www.mekawyerp.shop'],
)


# Application definition

INSTALLED_APPS = [
    # 'daphne' first makes `manage.py runserver` auto-serve ASGI (websockets) in dev —
    # see https://channels.readthedocs.io/en/stable/installation.html
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'widget_tweaks',
    'channels',
    'products',
    'crm',
    'accounts',
    'sales',
    'settings',
    'search_system', 
    'dashboard',
    'camera_view',
    'shipping',
    'financial',
    'notifications',
    'licensing',
    'restaurant',
    'attendance_devices',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT directly from Django/Daphne even with DEBUG=False and no
    # nginx/reverse proxy in front (runserver's DEBUG=True auto-serving stops working
    # the moment DEBUG=False — this replaces that for a standalone Daphne process, e.g.
    # the LAN test-run setup). Whitenoise is already in requirements.txt but was never
    # wired in here before, so DEBUG=False previously meant AND ALL static files 404.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.RequireOnboardingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SystemErrorCaptureMiddleware',
    'licensing.middleware.LicenseMiddleware',
]

ROOT_URLCONF = 'textile_pos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # التعديل هنا: نخبر جانغو بمكان مجلد القوالب الرئيسية
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'settings.context_processors.system_settings',
                'settings.context_processors.market_profile',
                'settings.context_processors.system_policies',
                'settings.context_processors.user_capabilities',
                'licensing.context_processors.license_info',
                'licensing.context_processors.feature_flags',
                'accounts.views.user_shortcuts_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'textile_pos.wsgi.application'
ASGI_APPLICATION = 'textile_pos.asgi.application'

# Live KDS / waiter-table-map / delivery updates (Phase 2). Defaults to the in-memory
# layer so dev/single-process runs work with zero extra infra. Set DJANGO_REDIS_URL
# (e.g. redis://127.0.0.1:6379/1) once Redis is available to support multiple workers —
# the in-memory layer only broadcasts within a single process.
_redis_url = os.environ.get('DJANGO_REDIS_URL', '')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DJANGO_DB_ENGINE', 'sqlite').lower() in ('postgres', 'postgresql'):
    # PostgreSQL — recommended for production / multi-cashier concurrency (Phase 0.3).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DJANGO_DB_NAME', 'wholesale_pos'),
            'USER': os.environ.get('DJANGO_DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # Path override lets tooling point at a throwaway DB (e.g. migration replay checks).
            'NAME': os.environ.get('DJANGO_SQLITE_NAME', str(BASE_DIR / 'db.sqlite3')),
            # Reduce 'database is locked' under concurrent POS writes on SQLite.
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Only length is still hard-enforced (6, not Django's default 8) — similarity-to-username,
# common-password, and numeric-only used to hard block a save with no way to override.
# Those are relegated to a non-blocking client-side hint (see the password-strength JS on
# the create-user / change-password templates) instead, per the store owner's request:
# weak is allowed through with a warning, not refused outright.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# يفضل تغيير اللغة للعربية لتتوافق مع لوحة تحكم الأدمن
LANGUAGE_CODE = 'ar' 

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Plain (non-manifest) storage — CompressedManifestStaticFilesStorage requires every
# template's {% static %} reference to exactly match a real collectstatic'd file or the
# whole page 500s; plain compressed storage degrades to "serves the file, just without
# cache-busting hashes" instead, which is what a temporary LAN test run wants.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (uploaded images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات تسجيل الدخول
LOGIN_REDIRECT_URL = 'dashboard'  # التوجيه بعد تسجيل الدخول
LOGOUT_REDIRECT_URL = 'login'     # التوجيه بعد تسجيل الخروج
LOGIN_URL = 'login'

# إعدادات الجلسة (Session) - 24 ساعة
SESSION_COOKIE_AGE = 86400  # 24 ساعة بالثواني (60*60*24)
SESSION_SAVE_EVERY_REQUEST = True # تجديد الجلسة مع كل طلب
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # إغلاق الجلسة عند إغلاق المتصفح لزيادة الأمان


# ──────────────────────────────────────────────
#  PRODUCTION SECURITY (active only when DEBUG=False)
# ──────────────────────────────────────────────
# These harden cookies/HTTPS in production while leaving local HTTP dev untouched.
# All of the HTTPS-only knobs below are individually env-overridable (not just gated on
# DEBUG) specifically so a DEBUG=False run over PLAIN HTTP — e.g. a LAN test on cafe
# hardware before real TLS is set up — can turn them off without going back to DEBUG=True.
# A "Secure" cookie is silently dropped by every browser over plain http:// — leaving
# SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE hardcoded True with no override meant login
# would look like it succeeds (200 response) but no session cookie ever gets stored, so
# the very next request is logged out again. SECURE_SSL_REDIRECT defaulting True would
# additionally force-redirect every plain http:// request to https://, which doesn't
# exist yet on a LAN test — a redirect loop / connection refused, not a login page.
if not DEBUG:
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # HTTPS / HSTS — enable once TLS is confirmed working on the domain.
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ──────────────────────────────────────────────
#  LOGGING — capture errors to file (and console)
# ──────────────────────────────────────────────
LOG_DIR = Path(os.environ.get('DJANGO_LOG_DIR', str(BASE_DIR / 'logs')))
LOG_DIR.mkdir(parents=True, exist_ok=True)

# The packaged desktop build runs windowed (console=False), so sys.stdout and sys.stderr
# are None. A StreamHandler attached to a missing stream raises AttributeError on the very
# first record, logging then tries to report THAT failure to a cp1252 stderr, and an Arabic
# message turns it into UnicodeEncodeError. The exception escapes whatever view was logging
# — which is how `logger.error(...)` inside submit_order_ajax's error handler turned an
# ordinary refused sale into an unhandled 500, an HTML error page, and a POS button that
# looked completely dead.
_CONSOLE_LOGGING_AVAILABLE = sys.stderr is not None and sys.stdout is not None
_LOG_HANDLERS = ['console', 'file'] if _CONSOLE_LOGGING_AVAILABLE else ['file']

# Belt and braces: logging must never be able to break a request, whatever the handler.
logging.raiseExceptions = False


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'app.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            # Without this the file handler uses the Windows ANSI codepage, and every log
            # line containing Arabic raises UnicodeEncodeError instead of being written.
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': _LOG_HANDLERS,
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': _LOG_HANDLERS,
            'level': 'INFO',
            'propagate': False,
        },
    },
}