# Generated by Django 5.2.15 on 2026-08-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: بصمة المدخل الرئيسي', max_length=100, verbose_name='اسم الجهاز')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, verbose_name='الشركة المصنّعة')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='موديل الجهاز')),
                ('adapter_type', models.CharField(max_length=50, verbose_name='بروتوكول/نوع الاتصال')),
                ('ip_address', models.CharField(blank=True, default='', max_length=100, verbose_name='عنوان IP / المضيف')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='المنفذ (Port)')),
                ('protocol', models.CharField(blank=True, default='', help_text='مثال: TCP, UDP, HTTP', max_length=30, verbose_name='بروتوكول الشبكة')),
                ('device_serial', models.CharField(blank=True, default='', max_length=100, verbose_name='الرقم التسلسلي للجهاز')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم المستخدم على الجهاز')),
                ('enabled', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('clear_after_sync', models.BooleanField(default=False, help_text='فعّلها فقط إذا كنت تريد حذف البصمات من ذاكرة الجهاز بعد سحبها بنجاح — إجراء لا رجعة فيه.', verbose_name='مسح السجلات من الجهاز بعد المزامنة')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة')),
                ('connection_status', models.CharField(choices=[('unknown', 'غير معروف'), ('online', 'متصل'), ('offline', 'غير متصل'), ('error', 'خطأ في الاتصال')], default='unknown', max_length=10, verbose_name='حالة الاتصال')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='آخر خطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جهاز حضور',
                'verbose_name_plural': 'أجهزة الحضور',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_secret_encrypted', models.TextField(blank=True, db_column='secret_encrypted', default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='attendance_devices.attendancedevice')),
            ],
            options={
                'verbose_name': 'بيانات اعتماد جهاز',
                'verbose_name_plural': 'بيانات اعتماد الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'جارٍ التنفيذ'), ('success', 'نجحت'), ('partial', 'نجحت جزئياً'), ('failed', 'فشلت')], default='running', max_length=10)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_skipped_duplicate', models.PositiveIntegerField(default=0)),
                ('records_unmapped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='attendance_devices.attendancedevice')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بدأها')),
            ],
            options={
                'verbose_name': 'سجل مزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=100, verbose_name='رقم المستخدم على الجهاز')),
                ('device_user_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المستخدم على الجهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='attendance_devices.attendancedevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to=settings.AUTH_USER_MODEL, verbose_name='الموظف في النظام')),
            ],
            options={
                'verbose_name': 'ربط موظف بجهاز',
                'verbose_name_plural': 'ربط الموظفين بالأجهزة',
                'indexes': [models.Index(fields=['device', 'device_user_id'], name='attendance__device__17c7c1_idx')],
                'unique_together': {('device', 'device_user_id')},
            },
        ),
        migrations.CreateModel(
            name='DevicePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=100, verbose_name='رقم المستخدم على الجهاز')),
                ('punch_timestamp', models.DateTimeField(verbose_name='وقت البصمة')),
                ('punch_type', models.CharField(choices=[('in', 'حضور'), ('out', 'انصراف'), ('unknown', 'غير محدد')], default='unknown', max_length=10, verbose_name='نوع البصمة')),
                ('verification_method', models.CharField(choices=[('fingerprint', 'بصمة إصبع'), ('face', 'بصمة وجه'), ('card', 'كارت'), ('pin', 'رقم سري'), ('unknown', 'غير محدد')], default='unknown', max_length=15, verbose_name='طريقة التحقق')),
                ('raw_reference', models.CharField(blank=True, default='', max_length=200, verbose_name='مرجع السجل الخام بالجهاز')),
                ('dedup_key', models.CharField(max_length=64, unique=True, verbose_name='مفتاح منع التكرار')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, verbose_name='تمت معالجته')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='attendance_devices.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, help_text='فارغ إذا لم يتم ربط رقم المستخدم على الجهاز بموظف بعد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_punches', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='attendance_devices.devicesynclog')),
            ],
            options={
                'verbose_name': 'بصمة حضور',
                'verbose_name_plural': 'بصمات الحضور',
                'ordering': ['-punch_timestamp'],
                'indexes': [models.Index(fields=['employee', 'punch_timestamp'], name='attendance__employe_c7e6af_idx'), models.Index(fields=['device', 'device_user_id'], name='attendance__device__34b37e_idx'), models.Index(fields=['processed'], name='attendance__process_b12b14_idx')],
            },
        ),
    ]
