# Generated by Django 5.2.15 on 2026-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='max_retries',
            field=models.PositiveIntegerField(default=2, help_text='عدد محاولات إعادة المزامنة تلقائياً بعد فشل الاتصال، قبل تسجيلها كفشل نهائي.', verbose_name='عدد محاولات إعادة الاتصال'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='retry_delay_seconds',
            field=models.PositiveIntegerField(default=5, verbose_name='الانتظار بين المحاولات (ثانية)'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=10, help_text='أقصى وقت انتظار عند محاولة الاتصال بالجهاز قبل اعتبارها فشلت.', verbose_name='مهلة الاتصال (ثانية)'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='timezone_name',
            field=models.CharField(default='Africa/Cairo', help_text='مثال: Africa/Cairo — اضبطها على المنطقة الزمنية الفعلية لساعة الجهاز.', max_length=64, verbose_name='المنطقة الزمنية للجهاز'),
        ),
    ]
