# Generated by Django 5.2.9 on 2025-12-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'قطاعي'), ('semi_wholesale', 'نص جملة'), ('wholesale', 'جملة')], default='retail', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
