# Generated by Django 5.2.9 on 2026-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_customer_type_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='أدخل قيمة موجبة (+) إذا كان عليه فلوس، وقيمة سالبة (-) إذا كان له رصيد', max_digits=12, verbose_name='رصيد افتتاحي (مديونية سابقة)'),
        ),
    ]
