# Generated by Django 6.0.5 on 2026-05-29 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('payment', 'سداد مديونية / إيداع'), ('debt', 'سحب مديونية / دين يدوي')], default='payment', max_length=20, verbose_name='نوع العملية')),
                ('payment_method', models.CharField(default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_log', to='crm.customer', verbose_name='العميل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'دفعة عميل',
                'verbose_name_plural': 'دفعات العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
