# Generated by Django 6.0.5 on 2026-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerpayment'),
        ('licensing', '0005_systemlicense_grace_period_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='licensing.masterstore', verbose_name='Master Store'),
        ),
    ]
