# Generated by Django 6.0.5 on 2026-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_master_store_customerpayment_master_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='master_store',
        ),
    ]
