# Generated by Django 6.0.5 on 2026-06-12 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_customer_master_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='أقصى مديونية مسموح بها. 0 يعني غير محدود.', max_digits=12, verbose_name='حد الائتمان (الدين المسموح)'),
        ),
    ]
