# Generated by Django 5.2.9 on 2026-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_market_features_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='رقم السند'),
        ),
    ]
