# Generated by Django 5.2.9 on 2026-06-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_backfill_receipt_vouchers'),
        ('sales', '0026_backfill_return_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.order', verbose_name='الفاتورة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.customerpayment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة',
                'verbose_name_plural': 'تخصيصات الدفعات',
            },
        ),
    ]
