# Generated by Django 5.2.9 on 2026-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_backfill_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='قائمة سوداء (إيقاف البيع الآجل)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم هاتف إضافي'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي (للشركات)'),
        ),
    ]
