# Generated by Django 5.2.15 on 2026-07-08 21:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0025_dealdiscount_categories'),
        ('products', '0034_category_code_range_end_category_code_range_start'),
        ('sales', '0037_draft_visa_paid_order_visa_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطيار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='products.warehouse', verbose_name='الفرع')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول')),
            ],
            options={
                'verbose_name': 'طيار / مندوب دليفري',
                'verbose_name_plural': 'الطيارين',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('waiter', 'ويتر'), ('driver', 'طيار دليفري'), ('other', 'أخرى')], max_length=10, verbose_name='النوع')),
                ('holder_name', models.CharField(max_length=100, verbose_name='اسم الشخص')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('held', 'معه (لم يُسلَّم)'), ('settled', 'تم التسليم')], db_index=True, default='held', max_length=10, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفتح')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_custodies', to='products.warehouse', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custodies', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('holder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_custodies', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('orders', models.ManyToManyField(blank=True, related_name='cash_custodies', to='sales.order', verbose_name='الفواتير المرتبطة')),
                ('settlement_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financial.transaction', verbose_name='حركة التسليم')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_custodies', to='financial.dailyshift', verbose_name='الشيفت')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodies', to='restaurant.driver', verbose_name='الطيار')),
            ],
            options={
                'verbose_name': 'وديعة',
                'verbose_name_plural': 'الودائع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحطة')),
                ('printer_target', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم/عنوان الطابعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stations', to='products.warehouse', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'محطة تحضير',
                'verbose_name_plural': 'محطات التحضير',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('is_required', models.BooleanField(default=False, verbose_name='إجباري')),
                ('min_select', models.PositiveIntegerField(default=0, verbose_name='أقل عدد اختيارات')),
                ('max_select', models.PositiveIntegerField(default=1, verbose_name='أقصى عدد اختيارات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('categories', models.ManyToManyField(blank=True, related_name='modifier_groups', to='products.category', verbose_name='الأقسام')),
                ('products', models.ManyToManyField(blank=True, related_name='modifier_groups', to='products.product', verbose_name='الأصناف')),
            ],
            options={
                'verbose_name': 'مجموعة اختيارات',
                'verbose_name_plural': 'مجموعات الاختيارات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاختيار')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='فرق السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurant.menumodifiergroup', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'اختيار',
                'verbose_name_plural': 'الاختيارات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات التحضير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='products.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'وصفة تحضير',
                'verbose_name_plural': 'وصفات التحضير',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_sections', to='products.warehouse', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'صالة',
                'verbose_name_plural': 'الصالات',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='products.product', verbose_name='الخامة')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.recipe', verbose_name='الوصفة')),
            ],
            options={
                'verbose_name': 'مكوّن وصفة',
                'verbose_name_plural': 'مكوّنات الوصفات',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الترابيزة')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='عدد الكراسي')),
                ('status', models.CharField(choices=[('free', 'متاحة'), ('busy', 'مشغولة'), ('reserved', 'محجوزة')], db_index=True, default='free', max_length=10, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='products.warehouse', verbose_name='الفرع')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurant.section', verbose_name='الصالة')),
            ],
            options={
                'verbose_name': 'ترابيزة',
                'verbose_name_plural': 'الترابيزات',
                'ordering': ['branch', 'section', 'number'],
                'unique_together': {('branch', 'number')},
            },
        ),
    ]
