# Generated by Django 5.2.15 on 2026-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='وحدة الكمية'),
        ),
    ]
