# Generated by Django 5.2.15 on 2026-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_recipeitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodifiergroup',
            name='show_on_receipt',
            field=models.BooleanField(default=True, verbose_name='يُطبع على فاتورة العميل'),
        ),
    ]
