# Generated by Django 5.2.15 on 2026-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menumodifiergroup_show_on_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserved_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم صاحب الحجز'),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved_notes',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved_party_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأفراد'),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد الحجز'),
        ),
    ]
