# Generated by Django 6.0.7 on 2026-07-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0037_category_is_menu_category"),
        ("restaurant", "0004_table_reserved_name_table_reserved_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="اسم الوصفة الفرعية"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات التحضير")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "وصفة فرعية",
                "verbose_name_plural": "الوصفات الفرعية",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubRecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="وحدة الكمية",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكوّن وصفة فرعية",
                "verbose_name_plural": "مكوّنات الوصفات الفرعية",
            },
        ),
        migrations.AlterUniqueTogether(
            name="recipeitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="recipe",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="products.size",
                verbose_name="الحجم",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="products.product",
                verbose_name="الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="recipeitem",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_recipes",
                to="products.product",
                verbose_name="الخامة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("product", "size")},
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="sub_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_recipes",
                to="restaurant.subrecipe",
                verbose_name="الوصفة الفرعية",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ingredient__isnull", False), ("sub_recipe__isnull", True)
                    ),
                    models.Q(
                        ("ingredient__isnull", True), ("sub_recipe__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="recipeitem_exactly_one_of_ingredient_or_subrecipe",
            ),
        ),
        migrations.AddField(
            model_name="subrecipeitem",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_subrecipes",
                to="products.product",
                verbose_name="الخامة",
            ),
        ),
        migrations.AddField(
            model_name="subrecipeitem",
            name="sub_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="restaurant.subrecipe",
                verbose_name="الوصفة الفرعية",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subrecipeitem",
            unique_together={("sub_recipe", "ingredient")},
        ),
    ]
