# Generated by Django 5.2.15 on 2026-08-09 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_track_stock_no_recipe'),
        ('restaurant', '0005_subrecipe_subrecipeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='modifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurant.menumodifier', verbose_name='الإضافة'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.product', verbose_name='الصنف'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modifier__isnull', True), ('product__isnull', False)), models.Q(('modifier__isnull', False), ('product__isnull', True)), _connector='OR'), name='recipe_exactly_one_of_product_or_modifier'),
        ),
    ]
