# Generated by Django 5.2.9 on 2026-01-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم شركة الشحن')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='اسم المندوب/المسؤول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شركة شحن',
                'verbose_name_plural': 'شركات الشحن',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('shipping', 'شحن لعنوان العميل'), ('pickup', 'استلام من الفرع')], default='shipping', max_length=20, verbose_name='طريقة التسليم')),
                ('shipping_address', models.TextField(verbose_name='عنوان الشحن')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='رقم البوليصة / التتبع')),
                ('status', models.CharField(choices=[('new', 'طلب جديد (تحت التجهيز)'), ('packaged', 'تم التغليف'), ('shipped', 'تم الشحن'), ('arrived', 'تم التوصيل'), ('returned', 'مرتجع')], default='new', max_length=20, verbose_name='حالة الشحن')),
                ('return_reason', models.TextField(blank=True, verbose_name='سبب الارتجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الشحنة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales.order', verbose_name='رقم الفاتورة')),
                ('shipping_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingcompany', verbose_name='شركة الشحن')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='الحالة')),
                ('comment', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shipping.shipment')),
            ],
        ),
    ]
