# Generated by Django 5.2.9 on 2026-07-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
