# Generated by Django 5.2.9 on 2026-07-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='balance_refunded',
            field=models.BooleanField(default=False, verbose_name='تم رد المبلغ لرصيد العميل'),
        ),
    ]
