# Generated by Django 5.2.9 on 2025-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_tailoring',
            field=models.BooleanField(default=False, verbose_name='طلب تفصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (Cash)'), ('wallet', 'محفظة ذكية (Wallet)'), ('instapay', 'Instapay')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المستلم'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='عنوان التوصيل/التفصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع الفرعي'),
        ),
        migrations.AddField(
            model_name='order',
            name='tailoring_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة التفصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='tailoring_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع التفصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
