# Generated by Django 5.2.9 on 2025-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_delivery_cost_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tailor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الترزي'),
        ),
        migrations.AddField(
            model_name='order',
            name='tailoring_status',
            field=models.CharField(choices=[('pending', 'لم يرسل بعد'), ('sent', 'تم الإرسال للترزي'), ('arrived', 'وصل من الترزي'), ('delivered', 'تم التسليم للعميل')], default='pending', max_length=20, verbose_name='حالة التفصيل'),
        ),
    ]
