# Generated by Django 5.2.9 on 2025-12-19 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_customer_type_alter_customer_phone'),
        ('products', '0002_stocktransaction_discount_and_more'),
        ('sales', '0003_order_tailor_name_order_tailoring_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / مقاسات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailoring_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع التفصيل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='بند الصرف')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب موظفين'), ('electricity', 'كهرباء/مياه/غاز'), ('internet', 'إنترنت وتليفون'), ('maintenance', 'صيانة وإصلاحات'), ('goods', 'نقل ومشال'), ('hospitality', 'ضيافة وبوفيه'), ('marketing', 'دعاية وإعلان'), ('other', 'نثريات / أخرى')], max_length=50, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي المبلغ المسترد')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الإرجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرجاع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer', verbose_name='العميل')),
                ('original_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order', verbose_name='الفاتورة الأصلية')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.returninvoice')),
            ],
        ),
    ]
