# Generated by Django 5.2.9 on 2025-12-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_orderitem_subtotal_alter_order_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الجرد')),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='النقدية المتوقعة (بالنظام)')),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='النقدية الفعلية (بالدرج)')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='العجز / الزيادة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات التسوية')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='القائم بالجرد')),
            ],
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: سداد دين، إيجار، إضافة رصيد', max_length=200, verbose_name='مصدر الدخل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
        ),
    ]
