# Generated by Django 5.2.9 on 2026-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_cashsettlement_otherincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (Cash)'), ('cod', 'دفع عند الاستلام (Cash on Delivery)'), ('wallet', 'محفظة إلكترونية (Vodafone Cash/Etisalat)'), ('instapay', 'InstaPay'), ('bank', 'تحويل بنكي (Bank Transfer)')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
