# Generated by Django 5.2.9 on 2026-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع نقدي'),
        ),
        migrations.AddField(
            model_name='order',
            name='instapay_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع InstaPay'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_online_order',
            field=models.BooleanField(default=False, verbose_name='طلب أونلاين'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع محفظة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (Cash)'), ('visa', 'فيزا (Visa)'), ('wallet', 'محفظة (Wallet)'), ('instapay', 'InstaPay'), ('cod', 'دفع عند الاستلام (COD)'), ('bank', 'تحويل بنكي (Bank Transfer)'), ('custom', 'مختلط/أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع الرئيسية'),
        ),
    ]
