# Generated by Django 5.2.9 on 2026-02-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_pieces_per_package'),
        ('sales', '0007_order_cash_paid_order_instapay_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse', verbose_name='المخزن'),
        ),
    ]
