# Generated by Django 5.2.9 on 2026-04-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_orderitem_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='warehouse',
        ),
    ]
