# Generated by Django 5.2.9 on 2026-04-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcosting'),
        ('sales', '0009_remove_orderitem_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse', verbose_name='المخزن'),
        ),
    ]
