# Generated by Django 5.2.9 on 2026-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'نسبة مئوية')], default='fixed', max_length=10, verbose_name='نوع الخصم'),
        ),
    ]
