# Generated by Django 6.0.5 on 2026-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sell_unit',
            field=models.CharField(default='box', max_length=20, verbose_name='وحدة البيع'),
        ),
    ]
