# Generated by Django 6.0.5 on 2026-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_orderitem_sell_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'نسبة مئوية')], default='fixed', max_length=10, verbose_name='نوع الخصم'),
        ),
    ]
