# Generated by Django 6.0.5 on 2026-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_draft_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='cash_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع نقدي'),
        ),
        migrations.AddField(
            model_name='draft',
            name='credit_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع من الرصيد'),
        ),
        migrations.AddField(
            model_name='draft',
            name='instapay_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع InstaPay'),
        ),
        migrations.AddField(
            model_name='draft',
            name='wallet_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع محفظة'),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع من الرصيد'),
        ),
    ]
