# Generated by Django 6.0.5 on 2026-05-22 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_shiftemaillog'),
        ('products', '0013_add_invoice_status_stock_audit'),
        ('sales', '0016_draft_cash_paid_draft_credit_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={},
        ),
        migrations.RemoveField(
            model_name='draft',
            name='name',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الوحدة (COGS)'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('converted', 'تم التحويل'), ('closed', 'مغلق')], default='open', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.dailyshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailoring_status',
            field=models.CharField(default='delivered', max_length=20, verbose_name='حالة التفصيل'),
        ),
    ]
