# Generated by Django 6.0.5 on 2026-05-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_dealdiscount_apply_to_all_dealdiscount_products'),
        ('sales', '0017_add_invoice_status_stock_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.dealdiscount', verbose_name='العرض المطبق'),
        ),
    ]
