# Generated by Django 6.0.5 on 2026-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_systemlicense_grace_period_started_at_and_more'),
        ('sales', '0018_order_applied_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsettlement',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_settlements', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='draft',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='expense',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_incomes', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='licensing.masterstore', verbose_name='Master Store'),
        ),
    ]
