# Generated by Django 6.0.5 on 2026-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_cashsettlement_master_store_draft_master_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsettlement',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='otherincome',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='returninvoice',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='master_store',
        ),
    ]
