# Generated by Django 5.2.9 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_cashsettlement_master_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'استرداد نقدي (من الدرج)'), ('customer_credit', 'إضافة لرصيد العميل (خصم من مديونيته)')], default='cash', max_length=20, verbose_name='طريقة الاسترداد'),
        ),
    ]
