# Generated by Django 5.2.9 on 2026-06-12 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_returninvoice_refund_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revision_no',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم المراجعة'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('void', 'ملغاة (Void)')], db_index=True, default='active', max_length=10, verbose_name='حالة الفاتورة'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddField(
            model_name='order',
            name='void_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_orders', to=settings.AUTH_USER_MODEL, verbose_name='ألغاها'),
        ),
        migrations.CreateModel(
            name='OrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='رقم المراجعة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('before_data', models.JSONField(verbose_name='بيانات الفاتورة قبل التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعديل')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عدّلها')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sales.order', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'مراجعة فاتورة',
                'verbose_name_plural': 'مراجعات الفواتير',
                'ordering': ['-created_at'],
            },
        ),
    ]
