# Generated by Django 5.2.9 on 2026-06-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_order_revision_no_order_status_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=10, verbose_name='نوع المستند')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='آخر رقم')),
            ],
            options={
                'verbose_name': 'تسلسل المستندات',
                'verbose_name_plural': 'تسلسلات المستندات',
                'unique_together': {('doc_type', 'year')},
            },
        ),
    ]
