# Generated by Django 5.2.9 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_backfill_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('defect', 'عيب صناعة / تالف'), ('wrong_item', 'صنف خاطئ'), ('size', 'مقاس غير مناسب'), ('changed_mind', 'العميل غيّر رأيه'), ('exchange', 'استبدال'), ('other', 'أخرى')], max_length=20, verbose_name='تصنيف السبب'),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='return_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='رقم المرتجع'),
        ),
    ]
