# Generated by Django 5.2.9 on 2026-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesman_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم البائع/المندوب'),
        ),
    ]
