# Generated by Django 5.2.9 on 2026-06-19 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_is_blacklisted_customer_phone2_and_more'),
        ('products', '0029_product_egs_code'),
        ('sales', '0028_order_salesman_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_orders', to='crm.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب محفوظ',
                'verbose_name_plural': 'طلبات محفوظة',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('sell_unit', models.CharField(default='box', max_length=10, verbose_name='وحدة البيع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('saved_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.savedorder', verbose_name='الطلب المحفوظ')),
            ],
        ),
    ]
