# Generated by Django 5.2.9 on 2026-06-20 10:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_is_blacklisted_customer_phone2_and_more'),
        ('products', '0029_product_egs_code'),
        ('sales', '0029_savedorder_savedorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='رقم الحجز')),
                ('status', models.CharField(choices=[('OPEN', 'محجوز (مفتوح)'), ('CONVERTED', 'تم التحويل لفاتورة'), ('CANCELLED', 'ملغي')], db_index=True, default='OPEN', max_length=10, verbose_name='الحالة')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='العربون')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_reservation', to='sales.order', verbose_name='الفاتورة الناتجة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.customer', verbose_name='العميل')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.reservation', verbose_name='الحجز')),
            ],
        ),
    ]
