# Generated by Django 5.2.9 on 2026-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الرقم التسلسلي'),
        ),
    ]
