# Generated by Django 5.2.9 on 2026-06-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_orderitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tailoring_status',
            field=models.CharField(choices=[('pending', 'لم يرسل بعد'), ('sent', 'تم الإرسال للترزي'), ('arrived', 'وصل من الترزي'), ('delivered', 'تم التسليم للعميل')], default='delivered', max_length=20, verbose_name='حالة التفصيل'),
        ),
    ]
