# Generated by Django 5.2.9 on 2026-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_alter_order_tailoring_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shortfall_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نقص المخزون وقت البيع'),
        ),
    ]
