# Generated by Django 5.2.9 on 2026-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_orderitem_shortfall_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_tier',
            field=models.CharField(choices=[('retail', 'قطاعي'), ('semi_wholesale', 'نص جملة'), ('wholesale', 'جملة')], default='retail', max_length=20, verbose_name='شريحة السعر'),
        ),
    ]
