# Generated by Django 5.2.9 on 2026-07-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_purchaseinvoiceitem_size_breakdown'),
        ('sales', '0035_orderitem_price_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='products.productvariant'),
        ),
    ]
