# Generated by Django 5.2.9 on 2026-07-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_returnitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='visa_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع فيزا'),
        ),
        migrations.AddField(
            model_name='order',
            name='visa_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مدفوع فيزا'),
        ),
    ]
