# Generated by Django 5.2.15 on 2026-07-08 21:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('sales', '0037_draft_visa_paid_order_visa_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='close_type',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('visa', 'فيزا'), ('cl', 'آجل (CL)')], default='', max_length=10, verbose_name='طريقة قفل الشيك'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='restaurant.driver', verbose_name='الطيار'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False, verbose_name='شيك مفتوح'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'صالة'), ('takeaway', 'تيك أواي'), ('delivery', 'دليفري')], db_index=True, default='dine_in', max_length=10, verbose_name='نوع الطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='نسبة/قيمة الخدمة'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.table', verbose_name='الترابيزة'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to=settings.AUTH_USER_MODEL, verbose_name='الويتر'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='ملغى'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('served', 'تم التقديم')], db_index=True, default='new', max_length=10, verbose_name='حالة التحضير'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list, verbose_name='الإضافات/الاختيارات'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='طُبع للمطبخ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='void_reason',
            field=models.TextField(blank=True, default='', verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_order_items', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه'),
        ),
    ]
