# Generated by Django 5.2.15 on 2026-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_order_close_type_order_driver_order_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('delivered', 'تم التسليم')], db_index=True, default='pending', max_length=10, verbose_name='حالة تحضير الطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بدء التحضير'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الجاهزية'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظة'),
        ),
    ]
