# Generated by Django 5.2.15 on 2026-07-10 23:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_order_delivered_at_order_kitchen_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة ضريبة القيمة المضافة'),
        ),
    ]
