# Generated by Django 5.2.15 on 2026-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_order_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الضريبة في المرتجع'),
        ),
    ]
