# Generated by Django 5.2.15 on 2026-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_returninvoice_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_included_snapshot',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل كانت الضريبة مضمنة وقت البيع'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الضريبة وقت البيع'),
        ),
    ]
