# Generated by Django 5.2.15 on 2026-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_order_vat_included_snapshot_order_vat_rate_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='close_type',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('visa', 'فيزا'), ('wallet', 'محفظة'), ('instapay', 'إنستا باي'), ('cl', 'آجل (CL)')], default='', max_length=10, verbose_name='طريقة قفل الشيك'),
        ),
    ]
