# Generated by Django 6.0.7 on 2026-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0043_alter_order_close_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت تعيين الطيار"
            ),
        ),
    ]
