# Generated by Django 6.0.7 on 2026-07-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0044_order_driver_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_settled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت استلام الطيار وتسليمه"
            ),
        ),
    ]
