# Generated by Django 5.2.15 on 2026-07-22 02:06

from django.db import migrations, models


def mark_existing_items_already_deducted(apps, schema_editor):
    # Every OrderItem created before this change already had its recipe ingredients
    # deducted at order time (the old behavior) — flag them all as done so the new
    # "deduct on kitchen ready" logic doesn't double-deduct their ingredients the next
    # time an in-flight ticket's status is touched.
    OrderItem = apps.get_model('sales', 'OrderItem')
    OrderItem.objects.update(recipe_deducted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_order_driver_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recipe_deducted',
            field=models.BooleanField(default=False, verbose_name='تم خصم مكونات الوصفة'),
        ),
        migrations.RunPython(mark_existing_items_already_deducted, migrations.RunPython.noop),
    ]
