# Generated by Django 5.2.15 on 2026-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_orderitem_recipe_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_void_acknowledged',
            field=models.BooleanField(default=False, verbose_name='تم استلام إلغاء المطبخ'),
        ),
    ]
