# Generated by Django 5.2.15 on 2026-08-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_orderitem_kitchen_void_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='split_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_invoices', to='sales.order', verbose_name='مقسمة من فاتورة'),
        ),
    ]
