# Generated by Django 5.2.15 on 2026-08-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_order_split_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_seats_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الكراسي وقت الطلب'),
        ),
    ]
