# Generated by Django 5.2.15 on 2026-08-14 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_order_table_seats_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تحويل بنكي'), ('wallet', 'محفظة إلكترونية'), ('instapay', 'إنستاباي')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='صورة الإيصال'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب موظفين'), ('electricity', 'كهرباء/مياه/غاز'), ('internet', 'إنترنت وتليفون'), ('maintenance', 'صيانة وإصلاحات'), ('cleaning', 'تنظيف ومستلزمات'), ('goods', 'نقل ومشال'), ('hospitality', 'ضيافة وبوفيه'), ('marketing', 'دعاية وإعلان'), ('other', 'نثريات / أخرى')], max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
    ]
