# Generated by Django 5.2.15 on 2026-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_seed_plain_invoice_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='رقم الفاتورة في الشيفت'),
        ),
    ]
