# Generated by Django 5.2.15 on 2026-09-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_expense_add_merchandise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب موظفين'), ('electricity', 'كهرباء/مياه/غاز'), ('internet', 'إنترنت وتليفون'), ('maintenance', 'صيانة وإصلاحات'), ('cleaning', 'تنظيف ومستلزمات'), ('goods', 'نقل ومشال'), ('hospitality', 'ضيافة وبوفيه'), ('marketing', 'دعاية وإعلان'), ('merchandise', 'بضاعة'), ('advance', 'سلفة موظفين'), ('other', 'نثريات / أخرى')], max_length=50, verbose_name='التصنيف'),
        ),
    ]
