# Generated by Django 5.2.9 on 2025-12-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة/المورد')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المسؤول')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('sku', models.CharField(help_text='الباركود أو كود المنتج الفريد', max_length=50, unique=True, verbose_name='كود المنتج / SKU')),
                ('material', models.CharField(blank=True, help_text='مثال: قطن، حرير، بوليستر', max_length=100, verbose_name='الخامة')),
                ('pattern', models.CharField(blank=True, help_text='مثال: كاروهات، مشجر، سادة', max_length=100, verbose_name='النقشة')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='اللون')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='سعر الشراء من المورد', max_digits=10, verbose_name='سعر التكلفة')),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر قطاعي')),
                ('price_semi_wholesale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر نص جملة')),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر جملة')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الكمية الحالية')),
                ('unit_measure', models.CharField(choices=[('MTR', 'متر'), ('YRD', 'ياردة'), ('ROLL', 'رول / توب'), ('PCS', 'قطعة'), ('KG', 'كيلوجرام')], default='MTR', max_length=4, verbose_name='وحدة القياس')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='حد التنبيه للنواقص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (متاح للبيع)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='القسم')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'إضافة للمخزن (شراء)'), ('OUT', 'سحب من المخزن (بيع)'), ('RET', 'مرتجع من عميل')], max_length=3, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'حركات المخزن',
            },
        ),
    ]
