# Generated by Django 5.2.9 on 2025-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة/المرجع'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
