# Generated by Django 5.2.9 on 2026-02-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stocktransaction_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المخزن')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_sales_point', models.BooleanField(default=False, verbose_name='منفذ بيع (يظهر في الكاشير)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي الكمية (كل المخازن)'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'إضافة للمخزن (شراء)'), ('OUT', 'سحب من المخزن (بيع)'), ('RET', 'مرتجع من عميل'), ('TRN', 'تحويل بين مخازن'), ('ADJ', 'تسوية جرد')], max_length=3, verbose_name='نوع الحركة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse', verbose_name='المخزن'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الكمية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'رصيد منتج في مخزن',
                'verbose_name_plural': 'أرصدة المخازن',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
