# Generated by Django 5.2.9 on 2026-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_warehouse_alter_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_package',
            field=models.PositiveIntegerField(default=48, help_text='عدد القطع في كل شيكارة (الافتراضي: 48)', verbose_name='قطع في الشيكارة'),
        ),
    ]
