# Generated by Django 5.2.9 on 2026-04-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchaseinvoice_supplierpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج (في الحساب)')),
                ('mode', models.CharField(choices=[('RETAIL', 'شراء (قطاعي)'), ('MANUFACTURE', 'تصنيع (إنتاج)')], max_length=20, verbose_name='نوع الحساب')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع المقترح')),
                ('config_json', models.JSONField(verbose_name='بيانات الحساب التفصيلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحساب')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costings', to='products.product', verbose_name='المنتج المرتبط')),
            ],
            options={
                'verbose_name': 'حسبة تكاليف',
                'verbose_name_plural': 'سجل حساب التكاليف',
                'ordering': ['-created_at'],
            },
        ),
    ]
