# Generated by Django 5.2.9 on 2026-04-29 10:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcosting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='المقاس')),
                ('size_type', models.CharField(choices=[('alpha', 'حروف (S/M/L)'), ('numeric', 'أرقام'), ('custom', 'مخصص')], default='alpha', max_length=10, verbose_name='نوع المقاس')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='الاختصار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='يُولَّد تلقائياً من SKU إن تُرك فارغاً', max_length=20, verbose_name='الباركود (EAN-13)'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='products.warehouse', verbose_name='المخزن الوجهة (للتحويل/التصنيع)'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stocktransaction', verbose_name='الحركة المرتبطة (تصنيع)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('RAW', 'مورد خامات'), ('FINISHED', 'مورد منتج نهائي'), ('BOTH', 'كلاهما')], default='FINISHED', max_length=10, verbose_name='نوع المورد'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('RAW', 'مخزن خامات'), ('FINISHED', 'مخزن منتج نهائي'), ('BOTH', 'كلاهما')], default='FINISHED', max_length=10, verbose_name='نوع المخزن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='كود المنتج الفريد', max_length=50, unique=True, verbose_name='كود المنتج / SKU'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'استلام شراء'), ('OUT', 'بيع'), ('RET', 'مرتجع من عميل (قديم)'), ('RET_IN', 'مرتجع من عميل'), ('RET_OUT', 'مرتجع لمورد'), ('TRN', 'تحويل بين مخازن'), ('MFG', 'تصنيع — خصم خامات'), ('MFG_OUT', 'تصنيع — إضافة منتج نهائي'), ('ADJ', 'تسوية جرد')], max_length=10, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='products.warehouse', verbose_name='المخزن'),
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='products.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'الأنواع',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.kind', verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(verbose_name='بيانات الصورة (base64)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم أمر الشراء')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('CONFIRMED', 'مؤكد'), ('PARTIAL', 'مستلم جزئياً'), ('RECEIVED', 'مستلم كلياً'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام المتوقع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي أمر الشراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.warehouse', verbose_name='مخزن الاستلام')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='products.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المطلوبة')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الكمية المستلمة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الخصم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseorder', verbose_name='أمر الشراء')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'صنف في أمر الشراء',
                'verbose_name_plural': 'أصناف أوامر الشراء',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.size', verbose_name='المقاسات'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size', verbose_name='المقاس'),
        ),
    ]
