# Generated by Django 5.2.9 on 2026-04-29 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_size_unitofmeasure_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='حد الائتمان'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رصيد افتتاحي'),
        ),
    ]
