# Generated by Django 6.0.5 on 2026-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_packaging_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم العلمي'),
        ),
        migrations.AddField(
            model_name='product',
            name='strips_per_box',
            field=models.PositiveIntegerField(default=1, help_text='لخدمة نظام الصيدليات', verbose_name='عدد الأشرطة في العلبة'),
        ),
    ]
