# Generated by Django 6.0.5 on 2026-05-19 18:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_shiftemaillog'),
        ('products', '0010_product_scientific_name_product_strips_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.account', verbose_name='الحساب المالي'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('bank', 'تحويل بنكي')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='products.warehouse', verbose_name='مخزن الاستلام'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('bonus_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='كمية البونص')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي الفرعي')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التشغيلة / الباتش')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseinvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صنف فاتورة مشتريات',
                'verbose_name_plural': 'أصناف فواتير المشتريات',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الباتش')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الشراء')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الأصلية')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الحالية')),
                ('is_exhausted', models.BooleanField(default=False, verbose_name='منتهي (كمية صفر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='المنتج')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='products.purchaseinvoice', verbose_name='فاتورة الشراء')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='المورد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'باتش مخزني',
                'verbose_name_plural': 'باتشات المخزن',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='آخر سعر شراء')),
                ('last_bonus_details', models.TextField(blank=True, verbose_name='تفاصيل آخر بونص')),
                ('supplier_sku', models.CharField(blank=True, max_length=100, verbose_name='كود المنتج عند المورد')),
                ('is_primary', models.BooleanField(default=False, verbose_name='مورد أساسي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سعر مورد لمنتج',
                'verbose_name_plural': 'أسعار الموردين للمنتجات',
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
