# Generated by Django 6.0.5 on 2026-05-19 18:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_shiftemaillog'),
        ('products', '0011_purchaseinvoice_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المرتجع')),
                ('refund_method', models.CharField(default='cash', max_length=20, verbose_name='طريقة استرداد المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.account', verbose_name='الحساب المالي (للإيداع)')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='products.purchaseinvoice', verbose_name='الفاتورة الأصلية')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='products.supplier', verbose_name='المورد')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='products.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'مرتجع مشتريات',
                'verbose_name_plural': 'مرتجع المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي الفرعي')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stockbatch', verbose_name='الباتش المتأثر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchasereturn', verbose_name='فاتورة المرتجع')),
            ],
            options={
                'verbose_name': 'صنف مرتجع مشتريات',
                'verbose_name_plural': 'أصناف مرتجع المشتريات',
            },
        ),
    ]
