# Generated by Django 6.0.5 on 2026-05-22 21:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_purchasereturn_purchasereturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_stock_applied',
            field=models.BooleanField(default=True, verbose_name='تم تطبيق المخزون'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة — لم يُضاف المخزون بعد'), ('CONFIRMED', 'مؤكد — تم إضافة المخزون'), ('CANCELLED', 'ملغي')], default='CONFIRMED', max_length=10, verbose_name='حالة الفاتورة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='سعر شراء الدفعة الفعلية وقت البيع — للحسابات الدقيقة للأرباح', max_digits=10, verbose_name='تكلفة الوحدة (COGS)'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر الوحدة (بيع)'),
        ),
    ]
