# Generated by Django 6.0.5 on 2026-05-23 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_invoice_status_stock_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصم'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الضريبة (%)'),
        ),
    ]
