# Generated by Django 6.0.5 on 2026-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_purchaseinvoiceitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة — لم يُضاف المخزون بعد'), ('CONFIRMED', 'مؤكد — تم إضافة المخزون'), ('RETURNED', 'مرتجع — تم إرجاع الفاتورة'), ('CANCELLED', 'ملغي')], default='CONFIRMED', max_length=10, verbose_name='حالة الفاتورة'),
        ),
    ]
