# Generated by Django 6.0.5 on 2026-05-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_purchaseinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='مثل: حليب 1 لتر، حليب 500 مل', verbose_name='له خيارات/أنواع مختلفة'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_weighted',
            field=models.BooleanField(default=False, help_text='للبقالة: منتجات تُباع بالوزن', verbose_name='منتج موزون (بالكيلو/غرام)'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='بالكيلوغرام أو اللتر', max_digits=10, null=True, verbose_name='الوزن الصافي'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_refrigeration',
            field=models.BooleanField(default=False, verbose_name='يحتاج تبريد'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الصلاحية (أيام)'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, help_text='مثل: 1 لتر، 500 مل، كبير، صغير', max_length=100, verbose_name='اسم الخيار'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product', verbose_name='المنتج الأصلي (للخيارات)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'كجم'), ('g', 'جرام'), ('l', 'لتر'), ('ml', 'ملليلتر')], max_length=10, verbose_name='وحدة الوزن/الحجم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('KG', 'كيلوغرام'), ('G', 'غرام'), ('L', 'لتر'), ('ML', 'مليلتر'), ('PCS', 'قطعة'), ('PACK', 'علبة'), ('DOZEN', 'دزينة'), ('BOTTLE', 'قنينة'), ('CAN', 'علبة معدنية'), ('BAG', 'كيس'), ('CRATE', 'قفص'), ('MTR', 'متر'), ('YRD', 'ياردة'), ('ROLL', 'رول / توب'), ('BOX', 'علبة'), ('STRIP', 'شريط'), ('AMP', 'أمبول')], default='PCS', max_length=10, verbose_name='وحدة القياس'),
        ),
    ]
