# Generated by Django 6.0.5 on 2026-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_has_variants_product_is_weighted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='الماركة/العلامة التجارية'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_refurbished',
            field=models.BooleanField(default=False, verbose_name='مستخدم أو مُجدد'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الموديل'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='المواصفات الفنية'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الضمان (أشهر)'),
        ),
    ]
