# Generated by Django 6.0.5 on 2026-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_systemlicense_grace_period_started_at_and_more'),
        ('products', '0017_product_brand_product_is_refurbished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_costings', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_items', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='licensing.masterstore', verbose_name='Master Store'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='master_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='licensing.masterstore', verbose_name='Master Store'),
        ),
    ]
