# Generated by Django 6.0.5 on 2026-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_master_store_product_master_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='productcosting',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='master_store',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='master_store',
        ),
    ]
