# Generated by Django 6.0.5 on 2026-06-12 03:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_category_master_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sub_unit',
            field=models.BooleanField(default=False, verbose_name='يباع بالتجزئة (الوحدة الفرعية)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_products', to='products.unitofmeasure', verbose_name='الوحدة الفرعية'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة الفرعية'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_units_per_main_unit',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='عدد الوحدات الفرعية داخل الوحدة الأساسية'),
        ),
    ]
