# Generated by Django 6.0.5 on 2026-06-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_has_sub_unit_product_sub_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('', 'غير محدد'), ('spring_summer', 'ربيع / صيف'), ('fall_winter', 'خريف / شتاء'), ('all_season', 'كل المواسم')], default='', help_text='للملابس: صيفي، شتوي، أو كل المواسم', max_length=20, verbose_name='الموسم'),
        ),
    ]
