# Generated by Django 5.2.9 on 2026-06-15 17:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_backfill_payment_vouchers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'قيد الجرد'), ('applied', 'تم الاعتماد')], default='draft', max_length=10, verbose_name='الحالة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_applied', to=settings.AUTH_USER_MODEL, verbose_name='اعتمدها')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='products.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'جرد مخزون',
                'verbose_name_plural': 'عمليات الجرد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رصيد النظام')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الجرد الفعلي')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
            ],
            options={
                'unique_together': {('count', 'product')},
            },
        ),
    ]
