# Generated by Django 5.2.9 on 2026-06-15 18:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_stockcount_stockcountitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مصاريف إضافية (شحن/جمارك)'),
        ),
    ]
