# Generated by Django 5.2.9 on 2026-06-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_purchaseinvoice_landed_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, choices=[('', 'كل الفئات'), ('retail', 'قطاعي'), ('semi_wholesale', 'نص جملة'), ('wholesale', 'جملة')], default='', max_length=20, verbose_name='فئة العميل')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='من كمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_breaks', to='products.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'شريحة سعر كمية',
                'verbose_name_plural': 'شرائح أسعار الكميات',
                'ordering': ['product', 'customer_type', 'min_quantity'],
            },
        ),
    ]
