# Generated by Django 5.2.9 on 2026-06-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productpricebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='egs_code',
            field=models.CharField(blank=True, default='', help_text='كود الصنف لمنظومة الفاتورة الإلكترونية. يُستخدم الباركود إن تُرك فارغاً.', max_length=30, verbose_name='كود الصنف الضريبي (EGS/GS1)'),
        ),
    ]
