# Generated by Django 5.2.9 on 2026-06-28 22:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_egs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_products', to='products.product', verbose_name='المنتج الأصلي (للخيارات)'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='اللون')),
                ('barcode', models.CharField(blank=True, default='', max_length=64, verbose_name='الباركود')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر خاص (اختياري)')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الكمية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='المنتج الأساسي')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'خيار منتج (مقاس/لون)',
                'verbose_name_plural': 'خيارات المنتجات',
                'ordering': ['product', 'size__sort_order', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
