# Generated by Django 5.2.9 on 2026-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_variant_parent_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=False, help_text='للإلكترونيات: يُطلب الرقم التسلسلي للقطعة عند البيع', verbose_name='يتطلب رقم تسلسلي عند البيع'),
        ),
    ]
