# Generated by Django 5.2.9 on 2026-07-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_is_serialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='size_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='تقسيم الكمية حسب المقاس'),
        ),
    ]
