# Generated by Django 5.2.9 on 2026-07-06 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_purchaseinvoiceitem_size_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_semi_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر نص جملة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر جملة'),
        ),
    ]
