# Generated by Django 5.2.15 on 2026-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_product_price_semi_wholesale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_range_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى كود'),
        ),
        migrations.AddField(
            model_name='category',
            name='code_range_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='من كود'),
        ),
    ]
