# Generated by Django 5.2.15 on 2026-07-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_category_code_range_end_category_code_range_start'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='restaurant.kitchenstation', verbose_name='محطة التحضير'),
        ),
    ]
