# Generated by Django 5.2.15 on 2026-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_category_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_raw_material',
            field=models.BooleanField(default=False, verbose_name='مادة خام (غير مباعة مباشرة)'),
        ),
    ]
