# Generated by Django 5.2.15 on 2026-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_is_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_menu_category',
            field=models.BooleanField(default=False, verbose_name='قسم منيو (يُحضّر عند الطلب - بدون تتبع مخزون)'),
        ),
    ]
