# Generated by Django 5.2.15 on 2026-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_category_is_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text='مثال: يحتوي على مكسرات، ألبان، جلوتين', max_length=200, verbose_name='مسببات الحساسية'),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات الحرارية'),
        ),
        migrations.AddField(
            model_name='product',
            name='serve_temperature',
            field=models.CharField(blank=True, choices=[('', 'غير محدد'), ('hot', 'ساخن'), ('cold', 'بارد'), ('room', 'حرارة الغرفة')], default='', max_length=10, verbose_name='درجة التقديم'),
        ),
    ]
