# Generated by Django 5.2.15 on 2026-07-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_allergens_product_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock_no_recipe',
            field=models.BooleanField(default=False, help_text='فعّله لصنف يُشترى جاهزًا (مثل مشروب معلب) بدل ما يتحضر من وصفة — هيتم تتبع كميته ويمكن إضافته من فاتورة مشتريات مثل المواد الخام.', verbose_name='لا يُحضّر من مواد خام'),
        ),
    ]
